sudo: false

git:
  depth: 1

matrix:
  include:
    - name: "Run Unit Tests"
      language: go
      go:
        - "1.12.1"
      install: true
      script:
        - GO111MODULE=on go test -coverprofile=coverage.txt -covermode=atomic -bench -race ./...
      after_success:
        - bash <(curl -s https://codecov.io/bash)
